# Generated by Django 4.2.10 on 2024-02-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('url', models.TextField(max_length=120)),
                ('post_title', models.CharField(max_length=120)),
                ('post', models.TextField()),
                ('img', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
