# Generated by Django 4.2.10 on 2024-03-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=120)),
                ('htegs', models.CharField(max_length=40)),
                ('htegs_post', models.CharField(max_length=40)),
                ('img_main', models.CharField(max_length=120)),
                ('img_type', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
