# Generated by Django 5.1.3 on 2024-12-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('url', models.TextField(max_length=120)),
                ('tegs', models.CharField(max_length=120)),
                ('post_title', models.CharField(max_length=120)),
                ('post', models.TextField()),
                ('img', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
