# Generated by Django 4.2.27 on 2026-09-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_article_img_alter_project_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='owner_name',
            field=models.CharField(default='Деев Егор', max_length=200, verbose_name='Имя владельца'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('languages', 'Languages'), ('backend', 'Backend'), ('ai', 'AI / LLM'), ('database', 'Database'), ('devops', 'DevOps'), ('frontend', 'Frontend'), ('tools', 'Tools')], max_length=20, verbose_name='Категория'),
        ),
    ]
