# Generated by Django 4.2.27 on 2026-10-01 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sitesettings_owner_name_alter_skill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=64, verbose_name='ID посетителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Уникальный просмотр',
                'verbose_name_plural': 'Уникальные просмотры',
            },
        ),
        migrations.AlterUniqueTogether(
            name='articlelike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='ip_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Хэш IP'),
        ),
        migrations.AddField(
            model_name='articlelike',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID посетителя'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='ip_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Хэш IP'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='visitor_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ID посетителя'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='open_to_work',
            field=models.BooleanField(default=True, help_text='Показывать статус на главной', verbose_name='Открыт к предложениям'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='work_format',
            field=models.CharField(blank=True, default='Удалённо или гибрид, фриланс', max_length=100, verbose_name='Формат работы'),
        ),
        migrations.AlterField(
            model_name='articlelike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='articlelike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('article', 'user'), name='uniq_articlelike_user'),
        ),
        migrations.AddConstraint(
            model_name='articlelike',
            constraint=models.UniqueConstraint(condition=models.Q(('visitor_id', ''), _negated=True), fields=('article', 'visitor_id'), name='uniq_articlelike_visitor'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('comment', 'user'), name='uniq_commentlike_user'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(condition=models.Q(('visitor_id', ''), _negated=True), fields=('comment', 'visitor_id'), name='uniq_commentlike_visitor'),
        ),
        migrations.AddField(
            model_name='articleview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_views', to='main.article', verbose_name='Статья'),
        ),
        migrations.AlterUniqueTogether(
            name='articleview',
            unique_together={('article', 'visitor_id')},
        ),
    ]
